const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  CLEAR_CART: 'CLEAR_CART',
  ADD_TO_CART_START: 'ADD_TO_CART_START',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
  REMOVE_FROM_CART_START: 'REMOVE_FROM_CART_START',
  REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
  REMOVE_FROM_CART_FAILURE: 'REMOVE_FROM_CART_FAILURE',
  CLEAR_ITEM_FROM_CART_START: "CLEAR_ITEM_FROM_CART_START",
  CLEAR_ITEM_FROM_CART_SUCCESS: "CLEAR_ITEM_FROM_CART_SUCCESS",
  CLEAR_ITEM_FROM_CART_FAILURE: "CLEAR_ITEM_FROM_CART_FAILURE",
  PRELOAD_CART_DATA_SUCCESS: 'PRELOAD_CART_DATA_SUCCESS',
  PRELOAD_CART_DATA_FAILURE: 'PRELOAD_CART_DATA_FAILURE'
};

export default CartActionTypes;
